### ISSUE TITLE
JS errors when attempting to launch adminer

### ISSUE THREAD

**Issue by rolandsherwood2** [grabs/moodle-local_adminer#10]
Hi. Many thanks thanks for making this plugin available. Unfortunately, we are experiencing JS-related issues when attempting to make use of version 2020061000 under Moodle 3.9.1:

TypeError: $(...).modal is not a function[Learn More] index.php:2036:9
<anonymous>
https://<our site URL>/local/adminer/index.php:2036:9
execCb
https://<our site URL>/lib/javascript.php/1597842779/lib/requirejs/require.min.js:5:12859
check
https://<our site URL>/lib/javascript.php/1597842779/lib/requirejs/require.min.js:5:6613
enable
https://<our site URL>/lib/javascript.php/1597842779/lib/requirejs/require.min.js:5:9358
init
https://<our site URL>/lib/javascript.php/1597842779/lib/requirejs/require.min.js:5:5716
o/<
https://<our site URL>/lib/javascript.php/1597842779/lib/requirejs/require.min.js:5:11233
Content Security Policy: Ignoring “https://<our site URL>” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified

Any guidance you could offer would be much appreciated.

**Comment by grabs** [comment]
Hi,
thank you for reporting this!
Can you give me a little more information about your setup?
In your case:
- Which theme do you use?
- Do you use some sort of a hardened server which does block something?
- which version of PHP do you have?
- In what situation does the error occur?
Best regards
Andreas

**Comment by rolandsherwood2** [comment]
Hi Andreas,

Apologies for the late reply, and many thanks for looking into this issue!

Re. the information you requested: please find this as follows –


  *   Our theme is Space (https://themeforest.net/item/space-moodle-template/22579922), but the same issue occurs under Boost
  *   As far as we’re aware, no special changes have been made to the server (Ubuntu 18.04 w/ Apache, MySQL) which might fall under what you’re describing - in fact the server installation routine was pretty much identical to our Moodle 3.7 installation where the Adminer plugin functioned perfectly
  *   PHP version is: 7.2 (Ubuntu 18.04 default)
  *   The error occurs whenever an administrator user attempts to access the Moodle Adminer link from the site administration menu; please see the following video for a demonstration – https://box.xjtlu.edu.cn/f/fb5a55735f8b44f58915/?dl=1

Again, many thanks for any help you can offer with figuring out what’s happening here – it really is appreciated.

Best wishes,
Roland

Roland Sherwood
Manager
Educational Technologies Team
Educational Development Division (EDU)
Xi’an Jiaotong-Liverpool University
Tel. 512-88161212

My time zone is: China Standard Time (GMT +8)


[signature_2085451901]

XJTLU’s Educational Technologies Team offers a range of workshops<https://ice.xjtlu.edu.cn/course/view.php?id=877> designed to enhance your knowledge and skills in using ICE and other educational technologies. Browse the full catalogue and book a workshop for your academic unit here<https://ice.xjtlu.edu.cn/mod/questionnaire/view.php?id=41448>.

XJTLU’s Digital Learning Resources Hub<https://ice.xjtlu.edu.cn/course/view.php?id=691> can help you to create audio/video content for use in your teaching. Find out more and book a recording session here<https://ice.xjtlu.edu.cn/course/view.php?id=691>.

**Comment by grabs** [comment]
Hi Roland,
it looks like you're using an old version of the adminer and not the current version you mentioned in the first post.
Can you check that again.

And btw. could you please clean your post by removing all the old stuff. It makes it really hard to read.
Thank you!

Best regards
Andreas

**Comment by BLINGBOARD** [comment]
👍👍
