### ISSUE TITLE
Moodle server denies adminer connection

### ISSUE THREAD

**Issue by alcarola** [grabs/moodle-local_adminer#11]
Hi,

I was happily using Moodle Adminer on my Moodle server for quite some time, but when we recently upgraded the OS on the server (to Cent OS 8, from Cent OS 6), Adminer stopped working. Now I only get an error message that the Moodle server denied the connection.

We changed the database from mysql to MariaDB, and we thought that that perhaps was the problem, but now when I browsed the issues here, I saw that MariaDB is indeed supposed to work also in Moodle Adminer. (I knew from before that Adminer itself works wit MariaDB).

Adminer $plugin->version  = 2020061000;
Moodle $version  = 2020061502.01; 
(Both are updated with a git pull today.)

**Edit:** I also tried reinstalling the adminer plugin today, by removing it from the Moodle Plugins Overview and then letting Moodle reinstall the plugin.

I would be very grateful for any help with how to troubleshoot the problem!

Mikael

**Comment by grabs** [comment]
Hi Mikael,
thank you for reporting this!
When you wrote "the Moodle server denied the connection" did you mean "MariaDB server" or what error message is shown? Could you be a bit more specific on this?
I tried to reproduce this by installing moodle on a current CentOS 8 with Apache/PHP/MariaDB from the distribution.
The Adminer plugin runs without any problem in my environment.
Do you have a special setup for your LAMP stack?
Best regards
Andreas

**Comment by alcarola** [comment]
Hello!

Thank you very much for your interest in this issue, and for your prompt reply! I now see that the error is web browser specific.

In Moodle, when I click Site Administration -> Server -> Moodle Adminer, I get [this error using Chrome](https://www.dropbox.com/s/9vy0bcrtwuqdtc6/Chrome.png?dl=0)

Doing the same procedure in [Firefox, I get this](https://www.dropbox.com/s/8xogv41c1c3dvuv/Firefox.png?dl=0) more informative response.

In Firefox, when I click Open site in new window, Moodle Adminer indeed opens and I can access the database! (I use Ubuntu 20.04 on my desktop and both browsers are the latest versions available in the stable repositories today.)

I am not quite sure if the problem is our Moodle site or Moodle Adminer. I can of course work around the problem by using Firefox instead of Chrome to dig in the database, but it is perhaps not the most elegant solution.

The LAMP was set up by a university Linux admin. If there is some specific aspect of it that you need to know, then I can ask him.

Best regards,
Mikael

**Comment by grabs** [comment]
Hi Mikael,

it looks like there is a problem with embedding the adminer-site in a frame.
Maybe you have a web application firewall in front of your moodle-installation which injects some headers to prevent frame embedding.

Best regards
Andreas

**Comment by alcarola** [comment]
Hi,

Thank you very much for your help! It lead our sys admin on the right track and now the issue is solved! I post our solution here, in case somebody else has the same problem.

The “X-Frame-Options DENY” had been copied from an older installation, setting it to SAMEORIGIN fixed the issue.

I close this issue now.

Mikael
