### ISSUE TITLE
Moodle 3.11.15 - Adminer window much too small

### ISSUE THREAD

**Issue by francwalter** [grabs/moodle-local_adminer#14]
Hallo
I just installed the actual Plugin version (local_adminer_moodle42_2021051702.zip) on my local Moodle 3.11 installation, Moodle 3.11.15+ (Build: 20230629) and when I open it, the Adminer window is much too small, look:

![grafik](https://github.com/grabs/moodle-local_adminer/assets/927269/a3430eed-fc77-4979-8a3a-53b433ac42a1)

There are no resizing buttons to make it bigger.
On my online server I have 3.11.15 as well and here the same Adminer Plugin's window is big, so I dont think it is an issue with the old Moodle 3.11

Is there a way to resize it any bigger, to be able to use it better?

Thanks.frank

**Comment by grabs** [comment]
Hi, it seems you are using some plugin which throws some PHP notice or warning while you have debugging on.
Please try to disable debugging or try to fix the other plugin.
I hope this helps.
Best regards
Andreas
