### ISSUE TITLE
Missing text since Adminer v4.8.0

### ISSUE THREAD

**Issue by michael-milette** [grabs/moodle-local_adminer#15]
Hi @grabs ,

When I launch Adminer, all of the text appears is missing and numbers are replaced by question marks.

Adminer Tag: 4.7.8-mdl-39 works correctly in all supported versions of Moodle, even in the latest version of Moodle 4.3:
<img width="811" alt="image" src="https://github.com/grabs/moodle-local_adminer/assets/3808579/c3a7871d-04c6-48f2-8d89-908d389b237b">

However, all subsequent releases since then no longer show the text.
<img width="576" alt="image" src="https://github.com/grabs/moodle-local_adminer/assets/3808579/ae8361f2-52d1-4478-a6bc-cb1d006511f4">

In case it helps, I also noticed that there is a JavaScript error in the latest version (perhaps before that too - didn't check):
<img width="556" alt="image" src="https://github.com/grabs/moodle-local_adminer/assets/3808579/c9a7bb46-fd8a-43da-a311-cd543315de1d">

I am using MariaDB 10.4.28 on Windows. The above screenshots are from the same version of Moodle.

Things I've tried include:

- Moodle 4.0, 4.1, 4.2 and 4.3 with the Boost theme, in English on PHP 8.0 to 8.2.
- Uninstalling/Reinstalling.
- Purging cache.
- Clearing browser cache.
- Trying it in Chrome and Firefox (the latest releases for both).

Notes: 

Adminer 4.8.1 seems to work correctly on with MySQL 5.7.33 on Linux with PHP 7.4. I came across a post which describes the same issue. It claims that this may be fixed in the yet-to-be release of Adminer 4.8.2:
https://stackoverflow.com/questions/66989030/adminer-blank-gui-elements-running-on-mysql-8

Do you have any suggestions on why this might be happening with recent releases of Adminer for Moodle LMS, and perhaps what I can do to get around it?

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
Just found this link. Seems that v4.8.2 was released:
https://github.com/adminerevo/adminerevo/releases/tag/v4.8.2

**Comment by grabs** [comment]
@michael-milette ,

Thank you very much for this info! I didn't know this fork and I am glad you found it :).
The last version is now using AdminerEvo which seems to run fine on php 8.0 to 8.2 and Moodle 4.1 to 4.2.

Best regards
Andreas
