### ISSUE TITLE
Split permissions for adminer between read and write permissions

### ISSUE THREAD

**Issue by pd431** [grabs/moodle-local_adminer#19]
Currently, we have two usecases for adminer, whch differ between our production and test environments:
- [on test/prod] Run complex analysis and reports, to assist in troubleshooting, allocating resources or identify support needs.
- [on test] Fix issues at scale by performing fixes through sql queries.

The current issue is the level of access for adminer is read/write, meaning that granting anyone adminer access on production risks them performing a write operation that could damage the site or the data upon it.

Ideally, we would configure adminer to run as read-only on our prod environment, and have two levels of secret for test, one for read-only access, and one for read-write, to reflect different levels of risk.

**Comment by grabs** [comment]
Hi, I understand your desire to have a read only restriction for some users. But unfortunately there is no way to do such thing within adminer itself. The restrictions in adminer are defined by the restrictions of the database user with whom adminer establishes the connection to the database.
