### ISSUE TITLE
Adminer icon in the navigation bar

### ISSUE THREAD

**Issue by ralf-krause** [grabs/moodle-local_adminer#20]
Hi Andreas,
I think that the Adminer icon should not be shown in the navigation bar if the admin is logged out. I can't say if this could be a security issue but opening the database from everywhere could be a problem.
Ralf

**Comment by grabs** [comment]
Hi Ralf, thank you very much. I fixed it.
Best Andreas

**Comment by ralf-krause** [comment]
Thanks! 
It works for me in Moodle 4.4 and Moodle 5.0dev.
I just translated all new strings for the german lang pack de.
Best regards, Ralf

**Comment by grabs** [comment]
Thanks a lot for that too :).
I really appreciate this!
