### ISSUE TITLE
AMOS does not have English language strings for the Moodle 3.3 branch of local_adminer

### ISSUE THREAD

**Issue by germanvaleroelizondo** [grabs/moodle-local_adminer#8]
Hi,

When I was translating in AMOS the English language strings for the local-adminer plugin, I noticed that AMOS does not have the strings for the 3.3 branch version  of this plugin.

According to the documentation in https://docs.moodle.org/dev/Translating_plugins#If_translations_are_available_in_AMOS_for_some_Moodle_branches_but_not_available_for_other_branches , "The cause is very likely a programming error (see 'Plugins with coding errors' above), that must be fixed by the plugin maintainer. ".

Thanks in advance for your help.

**Comment by grabs** [comment]
Hi,
thanks for telling me. But unfortunately I don't know what I am missing here :(. There are just two strings and these are the same like in all versions before.
Maybe you have an idea.

**Comment by germanvaleroelizondo** [comment]
Hi Andreas,

I am afraid I am only a translator. Your lang/en/local_adminer.php file looks fine with just the two strings :)

And the funny thing is that when I tested it in a local 3.3.1 server, the two strings did have the correct es_mx translations working for my site. So, maybe it is just a strange behaviour.

btw: When I used the local code checker plugin (https://moodle.org/plugins/local_codechecker ) to check your plugin, it reported 30885 errors and 1098 warnings. I do not know whether any of those are serious or not :(

Your adminer plugin is used by more than one thousand Moodle sites, and it seems to be working very well for them.

**Comment by grabs** [comment]
Hi,
the errors and warnings are caused by the minified adminer library. This file is a compiled version and doesn't fit any coding rules ;).
A few errors come 
Best regards

**Comment by germanvaleroelizondo** [comment]
Many thanks for the explanation Andreas.

**Comment by germanvaleroelizondo** [comment]
Closing this issue now.
