### ISSUE TITLE
Migration from MariaDB to PostgreSQL - Fatal login error

### ISSUE THREAD

**Issue by davidpesce** [grabs/moodle-local_adminer#9]
Running Moodle 3.6.2+
Recently migrated to PostgreSQL from MariaDB and the site itself works fine, but Adminer gives me the following error:

```
Unable to connect to PostgreSQL server: FATAL: database "postgres" does not exist
```

I haven't dug into the code, but it seems like the db user is hardcoded to the value "postgres"?

**Comment by grabs** [comment]
Hi David,
I am sorry, that you have trouble running adminer. Of course there is no hard coded database name in my part of the code. Maybe it is in adminer itself. But it shouldn't matter anyway. I use this plugin in several moodle dev-systems. And all of them have different database names and access data.
Do you use the latest version of local_adminer?
Can you provide some more information?
What postgresql version do you use?
What local_adminer version do you use?
How did you migrate your database?

Best regards
Andreas

**Comment by davidpesce** [comment]
Hi Andreas,

Yeah, I don't think it's postgreSQL, but rather the migration between MariaDB and PostgreSQL. I used the Moodle database migration tool. 

PostgreSQL version is 11.2
Adminer: 3.4 (2018042100) (2018042100) - only because the latest version says beta release. Is it stable?

**Comment by grabs** [comment]
Hi David,
your local_adminer version is a bit old and should be updated.
All my adminer versions still are labeled "beta" because I use the external source from adminer which I have to adapt to moodle. But I'm thinking about making it stable.
So give it a try ;).
Best regards
Andreas

**Comment by davidpesce** [comment]
Worked like a charm! Thank you!!
